//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NArchitecture.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NArchitecture.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} cannot be null or empty..
        /// </summary>
        internal static string ArgumentEmptyException {
            get {
                return ResourceManager.GetString("ArgumentEmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot handle request of type {0}..
        /// </summary>
        internal static string CannotHandleRequest {
            get {
                return ResourceManager.GetString("CannotHandleRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no or too many handlers to handle the request..
        /// </summary>
        internal static string NoneOrTooManyRequestHandlers {
            get {
                return ResourceManager.GetString("NoneOrTooManyRequestHandlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy needs to have at least one authorization requirement..
        /// </summary>
        internal static string PolicyHasNoRequirements {
            get {
                return ResourceManager.GetString("PolicyHasNoRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No policy found: {0}..
        /// </summary>
        internal static string PolicyNotFound {
            get {
                return ResourceManager.GetString("PolicyNotFound", resourceCulture);
            }
        }
    }
}
