version: '0.1.{build}'

environment:
  COVERALLS_REPO_TOKEN:
    secure: IRUBTX12n3W43fS0cgsX0h4I1fjO8XUxt7gNlDIoCrGMpVSW6BSDscCEwHJEEy57

branches:
  only:
    - master

cache:
  - packages

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'

before_build:
  - nuget restore

build:
  project: NArchitecture.sln

after_build:
  - nuget pack .\NArchitecture\NArchitecture.csproj

after_test:
  - cmd: .\coverage.cmd

artifacts:
  - path: '*.nupkg'
